- name: Stop METEOR {{serviceName}}
  service:
    name: "{{serviceName}}"
    state: stopped

- name: Copie du jar
  copy:
    src: ~/rocketMotorDesign/target/RocketMotorDesign.jar
    dest: "/home/{{serviceName}}/RocketMotorDesign.jar"

- name: Start METEOR {{serviceName}}
  service:
    name: "{{serviceName}}"
    state: started
