- name: Activation page maintenance
  shell: "/root/scripts/meteor-maintenance.sh {{serviceName}} stopBack"

- name: Stop METEOR {{serviceName}}
  service:
    name: "{{serviceName}}"
    state: stopped

- name: Copie du jar
  copy:
    src: ~/rocketMotorDesign/target/RocketMotorDesign.jar
    dest: "/home/{{serviceName}}/RocketMotorDesign.jar"

- name: Start METEOR {{serviceName}}
  service:
    name: "{{serviceName}}"
    state: started

- name: Desactivation page maintenance
  shell: "sleep 35 && /root/scripts/meteor-maintenance.sh {{serviceName}} startBack"
