version: 2.1
jobs:
  build-and-test:
    working_directory: ~/rocketMotorDesign
    resource_class: large
    docker:
      - image: maven:3.8.4-openjdk-17
    steps:
      - run: |
            java -version
      - checkout # check out source code to working directory
      - restore_cache:
          key: rocketMotorDesign-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: rocketMotorDesign-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run: mvn verify
      - persist_to_workspace:
          root: ~/
          paths:
            - rocketMotorDesign
            - .m2
      - store_test_results:
          path: target/surefire-reports
  package:
    working_directory: ~/rocketMotorDesign
    docker:
      - image: maven:3.8.4-openjdk-17
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run: mvn package -DskipTests
      - store_artifacts:
          path: target/RocketMotorDesign.jar
      - persist_to_workspace:
          root: ~/rocketMotorDesign
          paths:
            - target
            - ansible
  deploy:
    working_directory: ~/rocketMotorDesign
    docker:
      - image: quay.io/ansible/ansible-runner:stable-2.12-latest
    environment:
      ANSIBLE_HOST_KEY_CHECKING: 'false'
    parameters:
      serviceName:
        type: string
        default: "meteor-ci"
    steps:
      - add_ssh_keys:
          fingerprints:
            - "fb:23:4a:84:80:aa:e9:ec:e5:84:73:2f:1b:43:88:2a"
      - attach_workspace:
          at: ~/rocketMotorDesign
      # SSH-KEYSCAN permet d'autoriser la clÃ© du server distant (open-sky)
      - run: |
          ssh-keyscan -H open-sky.fr >> ~/.ssh/known_hosts
      - run:
          name: Playbook time
          command: |
            cd ~/rocketMotorDesign/ansible
            ansible-playbook -i inventory open-sky.fr.yml --extra-vars serviceName=<<parameters.serviceName>>
workflows:
  version: 2
  build-test-and-approval-package:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /^v.*/
      - package:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
            tags:
              only: /^v.*/
      - deploy:
          name: deploy-ci
          requires:
            - package
          filters:
            tags:
              ignore: /.*/
      - hold-deploy-prod:
          type: approval
          requires:
            - package
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
      - deploy:
          name: deploy-prod-manual
          serviceName: "meteor"
          requires:
            - hold-deploy-prod
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
      - deploy:
          name: deploy-prod-auto-tag
          serviceName: "meteor"
          requires:
            - package
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
