version: 2
jobs:
  build-and-test:
    working_directory: ~/rocketMotorDesign
    machine: true
    steps:
      - checkout # check out source code to working directory
      - restore_cache:
          key: rocketMotorDesign-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: rocketMotorDesign-{{ checksum "pom.xml" }}
      - run: mvn test
  package-deploy:
    working_directory: ~/rocketMotorDesign
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: rocketMotorDesign-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: rocketMotorDesign-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_artifacts:
          path: target/RocketMotorDesign.jar
      - add_ssh_keys:
          fingerprints:
            - "fb:23:4a:84:80:aa:e9:ec:e5:84:73:2f:1b:43:88:2a"
      - run:
          name: Install Ansible
          command: |
            sudo apt update -y
            sudo apt install -y language-pack-ja-base language-pack-ja
            sudo apt install -y software-properties-common
            sudo apt-add-repository -y ppa:ansible/ansible
            sudo apt update -y
            sudo apt install -y curl python-dev git
            sudo curl "https://bootstrap.pypa.io/get-pip.py" -o "/tmp/get-pip.py"
            sudo python /tmp/get-pip.py
            sudo pip install --upgrade pip && pip install --upgrade setuptools
            sudo pip install ansible
      - run:
          name: Playbook time
          command: |
            cd ~/rocketMotorDesign/ansible
            ansible-playbook -i inventory open-sky.fr.yml
workflows:
  version: 2
  build-test-and-approval-package:
    jobs:
      - build-and-test
      - package-deploy:
          requires:
            - build-and-test