version: 2
jobs:
  build-and-test:
    working_directory: ~/rocketMotorDesign
    machine: true
    steps:
      - checkout # check out source code to working directory
      - restore_cache:
          key: rocketMotorDesign-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: rocketMotorDesign-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run: mvn test
      - persist_to_workspace:
          root: ~/
          paths:
            - rocketMotorDesign
            - .m2
  package:
    working_directory: ~/rocketMotorDesign
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run: mvn package
      - store_artifacts:
          path: target/RocketMotorDesign.jar
      - persist_to_workspace:
          root: ~/rocketMotorDesign
          paths:
            - target
            - ansible
  deploy:
    working_directory: ~/rocketMotorDesign
    docker:
      - image: ansible/ansible-runner
    steps:
      - add_ssh_keys:
          fingerprints:
            - "fb:23:4a:84:80:aa:e9:ec:e5:84:73:2f:1b:43:88:2a"
      - attach_workspace:
          at: ~/rocketMotorDesign
      # SSH-KEYSCAN permet d'autoriser la clÃ© du server distant (open-sky)
      - run: |
          ssh-keyscan -H open-sky.fr >> ~/.ssh/known_hosts
      - run:
          name: Playbook time
          command: |
            cd ~/rocketMotorDesign/ansible
            ansible-playbook -i inventory open-sky.fr.yml
workflows:
  version: 2
  build-test-and-approval-package:
    jobs:
      - build-and-test
      - package:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - package