version: 2
jobs:
  build-and-test:
    working_directory: ~/rocketMotorDesign
    machine: true
    steps:
      - checkout # check out source code to working directory
      - restore_cache:
          key: rocketMotorDesign-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: rocketMotorDesign-{{ checksum "pom.xml" }}
      - run: mvn test
  package:
    working_directory: ~/rocketMotorDesign
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: rocketMotorDesign-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: rocketMotorDesign-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_artifacts:
          path: target/RocketMotorDesign.jar
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: ~/rocketMotorDesign
          # Must be relative path from root
          paths:
            - target
            - ansible
  deploy:
    working_directory: ~/rocketMotorDesign
    docker:
      - image: ansible/ansible-runner
    steps:
      - add_ssh_keys:
          fingerprints:
            - "fb:23:4a:84:80:aa:e9:ec:e5:84:73:2f:1b:43:88:2a"
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/rocketMotorDesign
      - run: |
          ls -alh ~/rocketMotorDesign
          ssh-keyscan -H open-sky.fr >> ~/.ssh/known_hosts
      - run:
          name: Playbook time
          command: |
            cd ~/rocketMotorDesign/ansible
            ansible-playbook -i inventory open-sky.fr.yml
workflows:
  version: 2
  build-test-and-approval-package:
    jobs:
      - build-and-test
      - package:
          requires:
            - build-and-test
      - deploy:
          requires:
            - package