version: 2
jobs:
  build-and-test:
    working_directory: ~/rocketMotorDesign
    machine: true
    steps:
      - checkout # check out source code to working directory
      - restore_cache:
          key: rocketMotorDesign-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: rocketMotorDesign-{{ checksum "pom.xml" }}
      - run: mvn test
  package:
    working_directory: ~/rocketMotorDesign
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: rocketMotorDesign-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: rocketMotorDesign-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_artifacts:
          path: target/RocketMotorDesign.jar
workflows:
  version: 2
  build-test-and-approval-package:
    jobs:
      - build-and-test
      - hold:
          type: approval
          requires:
            - build-and-test
          filters:
            tags:
              only: /v.*/
      - package:
          requires:
            - hold