#commande pour demarrer tous les services: docker-compose up
version: "2.1"

services:
  prometheus:
    image: prom/prometheus:v2.11.1
    volumes:
      - ./prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  gafana:
    image: grafana/grafana:6.3.2
    ports:
      - "5000:3000"
    volumes:
      - ./grafana:/var/lib/grafana

  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql:/etc/mysql/conf.d
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=meteor_dev